name: Cypress

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  demo-chrome-tests:
    if: "contains(github.event.head_commit.message, 'cy ci')"

    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - run: npx cypress info

      - name: "Demo Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          browser: chrome

  demo-chrome-mobile-tests:
    if: "contains(github.event.head_commit.message, 'cy ci')"

    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - run: npx cypress info

      - name: "Demo Tests - Chrome - Mobile"
        uses: cypress-io/github-action@v2
        with:
          config: "viewportWidth=375,viewportHeight=667"
          browser: chrome

  demo-firefox-tests:
    if: "contains(github.event.head_commit.message, 'cy ci')"

    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome89-ff86
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - run: npx cypress info

      - name: "Demo Tests - Firefox"
        uses: cypress-io/github-action@v2
        with:
          browser: firefox

  demo-firefox-mobile-tests:
    if: "contains(github.event.head_commit.message, 'cy ci')"

    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome89-ff86
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - run: npx cypress info

      - name: "Demo Tests - Firefox - Mobile"
        uses: cypress-io/github-action@v2
        with:
          config: "viewportWidth=375,viewportHeight=667"
          browser: firefox

  demo-windows-tests:
    if: "contains(github.event.head_commit.message, 'cy ci')"

    runs-on: windows-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Get npm cache directory
        id: npm-config-get-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-config-get-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - run: npx cypress info

      - name: "Demo Tests - Electron - Windows"
        uses: cypress-io/github-action@v2
